name: Create PKGBUILD and create new release

on:
  push:
    paths:
      - 'release-versions/**'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Create PKGBUILD and submit to AUR
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Docker Container and create PKGBUILD from template
        uses: ./jellyfin-appimage/
      - name: Commit PKBUILD and .SRCINFO
        uses: EndBug/add-and-commit@v4
        with:
          add: 'jellyfin-appimage/PKGBUILD jellyfin-appimage/.SRCINFO'
          author_name: peterge1998
          author_email: mail@peterge.de
          message: 'Add generated PKBUILD and .SRCINFO'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: jellyamp-appimage
          pkgbuild: jellyfin-appimage/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519